- name: Retrieve hosts from Ledger Pro
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    cve: ""
    ledger_url: ""
  tasks:
    - name: Assert that CVE / Ledger URL is not blank
      ansible.builtin.assert:
        that:
          - cve != ''
          - ledger_url != ''

    - name: Connect to Ascender Pro to retreive 
      ansible.builtin.uri:
        url: "{{ ledger_url }}/api/v1/errata/cve/{{ cve }}/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: true
      register: cve_data

    - set_fact:
        hosts: "{{ cve_data.json.hosts | select('in', hostvars.keys() | list) | list }}"
        packages: "{{ cve_data.json.rpms | flatten }}"

    - debug:
        var: hosts

- name: Update vulnerable packages
  hosts: "{{ hostvars['localhost'].hosts }}"
  become: true
  tasks:
    - name: Gather Package Facts before patching
      ansible.builtin.package_facts:
        manager: auto
      when: ansible_os_family != 'Windows'

    - name: Install Updates
      ansible.builtin.dnf:
        name: "{{ hostvars['localhost'].packages | select('in', ansible_facts.packages.keys() | list) | list }}"
        state: latest
      register: updates

    - name: Gather Package Facts after patching
      ansible.builtin.package_facts:
        manager: auto
      when: ansible_os_family != 'Windows'
