---
- name: Randomly fail 1/3 of the time
  hosts: all
  gather_facts: false
  tasks:
    - assert:
        that:
          - "(range(0, 3) | random) != 0"
        fail_msg: "Random failure triggered."
        success_msg: "Passed random check."
